/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: kand8998 (https://sketchfab.com/KaitlynAndrus)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/eye-textured-ad4315627fb04ab3aa2a663973db9f89
title: Eye (Textured)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function EyeModel({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/resources/models/eye/eye.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Cleareye} />
          <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.Cornea} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/eye.gltf')

