/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/resources/models/objects/Mesa.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.SM_Laboratory_Table_3.geometry} material={materials.Inst_Tables_and_Curbstone_01} position={[5.89, 0.5, -5.5]} rotation={[0, -1.57, 0]} scale={0.01} />
      <mesh geometry={nodes.SM_Medical_Curbstone_Drawer_10.geometry} material={materials.Inst_Laboratory_Furniture_03} position={[5.57, 1.09, -6.27]} rotation={[0, -1.57, 0]} scale={0.01} />
      <mesh geometry={nodes.SM_Medical_Curbstone_Drawer_11.geometry} material={materials.Inst_Laboratory_Furniture_03} position={[5.57, 1.09, -5.75]} rotation={[0, -1.57, 0]} scale={0.01} />
      <mesh geometry={nodes.SM_Medical_Curbstone_Drawer_12.geometry} material={materials.Inst_Laboratory_Furniture_03} position={[5.57, 1.09, -5.25]} rotation={[0, -1.57, 0]} scale={0.01} />
      <mesh geometry={nodes.SM_Table_on_Wheels_01.geometry} material={materials.Inst_Table_on_Wheels_01} position={[5.87, 0.5, -4.22]} rotation={[0, -1.57, 0]} scale={0.01} />
      <mesh geometry={nodes.S_VasoDappen.geometry} material={materials.MI_VasoDappen} position={[5.87, 1.26, -3.9]} rotation={[0, -1.57, 0]} scale={0.01} />
      <mesh geometry={nodes.S_VasoDappen2.geometry} material={materials.MI_VasoDappen} position={[5.93, 1.26, -3.92]} rotation={[0, -1.57, 0]} scale={0.01} />
      <mesh geometry={nodes.SM_Salver_02.geometry} material={materials.Inst_Pallets} position={[6.01, 1.35, -5.01]} rotation={[0, -1.57, 0]} scale={0.01} />
      <mesh geometry={nodes.SM_Salver_3.geometry} material={materials.Inst_Pallets} position={[5.83, 1.35, -4.26]} rotation={[0, -1.57, 0]} scale={[0.02, 0.01, 0.01]} />
      <mesh geometry={nodes.SM_Salver_4.geometry} material={materials.Inst_Pallets} position={[5.63, 1.35, -5.01]} rotation={[0, -1.57, 0]} scale={0.01} />
      <mesh geometry={nodes.S_Basurero.geometry} material={materials.MI_Basurero} position={[6.07, 1.25, -5.09]} scale={0.01} />
      <mesh geometry={nodes.PortaAmalgama.geometry} material={materials.PortaAmalgama_001} position={[5.68, 1.27, -5.12]} rotation={[0.26, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.S_EspatulaDeCemento.geometry} material={materials.MI_EspatulaCemento} position={[6.03, 1.3, -4.99]} rotation={[0, 0, -Math.PI / 2]} scale={[0.01, 0.01, 0.02]} />
      <mesh geometry={nodes.S_SondaPeriodontal.geometry} material={materials.MI_SondaPeridontal} position={[5.74, 1.38, -4.96]} rotation={[-Math.PI / 2, 0, -0.17]} scale={[0.02, 0.01, 0.02]} />
      <mesh geometry={nodes.S_EscobillaDeProfilaxis.geometry} material={materials.MI_EscobillaProfilaxis} position={[6.02, 1.26, -4.82]} rotation={[-Math.PI / 2, 0, -1.05]} scale={0.02} />
      <mesh geometry={nodes.S_Fresarios.geometry} material={materials.MI_Fresarios} position={[5.75, 1.27, -4.85]} rotation={[0, -Math.PI / 2, 0]} scale={0.01} />
      <mesh geometry={nodes.S_PastaProfilactica.geometry} material={materials.MI_PastaProfilactica} position={[5.78, 1.28, -4.99]} rotation={[0, Math.PI / 6, 0]} scale={0.01} />
      <mesh geometry={nodes.S_EyectorDesechable6.geometry} material={materials.MI_Eyector} position={[5.62, 1.26, -4.97]} rotation={[Math.PI / 2, 0, -0.17]} scale={0.01} />
      <mesh geometry={nodes.S_VasoDesechable6.geometry} material={materials.MI_VasoDesechable} position={[5.58, 1.29, -4.82]} scale={0.01} />
      <mesh geometry={nodes.S_CapsulaAmalgama3.geometry} material={materials.MI_CapsulaAmalgama} position={[5.95, 1.26, -4.85]} rotation={[-Math.PI / 2, 0, -0.17]} scale={0.01} />
      <mesh geometry={nodes.S_Copella.geometry} material={materials.MI_Copela} position={[5.98, 1.26, -4.48]} scale={0} />
      <mesh geometry={nodes.S_Torula.geometry} material={materials.MI_Algodon} position={[6.02, 1.29, -4.49]} rotation={[0, 0, 0.87]} scale={0.02} />
      <mesh geometry={nodes.S_Torula2.geometry} material={materials.MI_Algodon} position={[6, 1.25, -4.46]} rotation={[0, 0, 0.87]} scale={0.02} />
      <mesh geometry={nodes.S_Torula3.geometry} material={materials.MI_Algodon} position={[6, 1.26, -4.51]} rotation={[0, 0.87, 0.87]} scale={0.02} />
      <mesh geometry={nodes.S_Torula4.geometry} material={materials.MI_Algodon} position={[5.97, 1.28, -4.49]} rotation={[0, 0, 0.87]} scale={0.02} />
      <mesh geometry={nodes.S_Antiparras.geometry} material={materials.MI_Antiparras} position={[6.07, 1.25, -3.91]} rotation={[Math.PI, -1.22, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.S_Mortero_HP_Cylinder_004.geometry} material={materials.MI_Mortero} position={[5.71, 1.25, -3.96]} scale={0.01} />
      <mesh geometry={nodes.S_Mortero_HP_Cylinder_005.geometry} material={materials.MI_Mortero} position={[5.71, 1.25, -3.96]} scale={0.01} />
      <mesh geometry={nodes.S_CubetaMaxilarSupconAlginatoListo_HP_Cubeta_maxilar_su_e23460c.geometry} material={materials.M_Metal_Brushed_Nickel} position={[5.59, 1.34, -5.08]} rotation={[0, 0, Math.PI]} scale={0} />
      <mesh geometry={nodes.S_Vaso_solo_HP.geometry} material={materials.vaso_alguinato} position={[6.04, 1.28, -4.86]} scale={0} />
      <mesh geometry={nodes.S_TuboDeResinaCompuesta.geometry} material={materials.MI_TuboResinaCompuesta} position={[5.61, 1.37, -4.96]} rotation={[0, -Math.PI / 2, 0]} scale={0.01} />
      <mesh geometry={nodes.S_AlginatoParaImpresion_LP.geometry} material={materials.MI_BolsaAlginato} position={[6.06, 1.07, -5.07]} rotation={[0, -0.87, 0]} scale={0.01} />
      <mesh geometry={nodes.S_EspatulaDeAlginato.geometry} material={materials['Material.001']} position={[5.94, 1.26, -4.83]} rotation={[0, 0.7, 0]} scale={0.01} />
      <group position={[5.65, 1.37, -4.82]} scale={0.01}>
        <mesh geometry={nodes.S_AcidoOrtofosforico_1.geometry} material={materials.MI_Jeringas} />
        <mesh geometry={nodes.S_AcidoOrtofosforico_2.geometry} material={materials.MI_AcidoOrtofosforico} />
      </group>
      <mesh geometry={nodes.S_DosificadorDeAguayPolvoOdontologia.geometry} material={materials.MI_PlasticAcrilico} position={[5.99, 1.27, -6.01]} scale={0.01} />
      <mesh geometry={nodes.S_AdhesivoOdontologia.geometry} material={materials.MI_AdhesivoDental} position={[5.95, 1.36, -5.07]} rotation={[0, -Math.PI / 3, 0]} scale={0.01} />
      <mesh geometry={nodes.S_pinzaMiller_HP.geometry} material={materials.M_Metal_Chrome} position={[5.68, 1.37, -4.98]} rotation={[-Math.PI / 2, 0, -Math.PI / 9]} scale={0} />
      <mesh geometry={nodes.S_MicroBrush.geometry} material={materials.MI_Microbrush} position={[5.55, 1.37, -4.9]} rotation={[-Math.PI / 2, 1.57, 0]} scale={0.01} />
      <group position={[6.09, 1.36, -5.04]} rotation={[Math.PI, -1.22, Math.PI]} scale={0}>
        <mesh geometry={nodes.S_LamparaFotocurado_HP_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.S_LamparaFotocurado_HP_2.geometry} material={materials.Material_001} />
        <mesh geometry={nodes.S_LamparaFotocurado_HP_3.geometry} material={materials.Material_003} />
        <mesh geometry={nodes.S_LamparaFotocurado_HP_4.geometry} material={materials.Material_002} />
        <mesh geometry={nodes.S_LamparaFotocurado_HP_5.geometry} material={materials.Material_004} />
        <mesh geometry={nodes.S_LamparaFotocurado_HP_6.geometry} material={materials.Material_005} />
      </group>
      <mesh geometry={nodes.S_FresasyGomasdePulido.geometry} material={materials.MI_FresasYGomasPulido} position={[5.97, 1.38, -4.89]} rotation={[-Math.PI, 0, -Math.PI]} scale={0} />
    </group>
  )
}

useGLTF.preload('/Mesa.glb')
