/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/resources/models/objects/Mesa_2.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.SM_Salver_3.geometry} material={materials.Inst_Pallets} position={[5.83, 8.39, -4.26]} rotation={[0, -1.57, 0]} scale={[0.18, 0.1, 0.14]}>
        <mesh geometry={nodes.SM_Salver_02_1.geometry} material={materials.Inst_Pallets} position={[-41.71, 0, -12.8]} scale={[0.67, 1, 0.75]} />
        <mesh geometry={nodes.SM_Salver_4.geometry} material={materials.Inst_Pallets} position={[-42.01, 0, 14.38]} scale={[0.67, 1, 0.75]} />
        <mesh geometry={nodes.PortaAmalgama.geometry} material={materials.PortaAmalgama_001} position={[-47.74, -8.23, 10.98]} rotation={[1.49, 1.27, -1.35]} scale={[0.71, 0.98, 0.6]} />
        <group position={[-31.58, 2.07, 12.87]} rotation={[0, 1.57, 0]} scale={[0.71, 1, 0.56]}>
          <mesh geometry={nodes.S_AcidoOrtofosforico_1.geometry} material={materials.MI_Jeringas} />
          <mesh geometry={nodes.S_AcidoOrtofosforico_2.geometry} material={materials.MI_AcidoOrtofosforico} />
        </group>
        <mesh geometry={nodes.S_AdhesivoOdontologia.geometry} material={materials.MI_AdhesivoDental} position={[-45.38, 1.35, -8.17]} rotation={[0, 0.53, 0]} scale={[0.37, 0.61, 0.41]} />
        <mesh geometry={nodes.S_AlginatoParaImpresion_LP.geometry} material={materials.MI_BolsaAlginato} position={[-45.4, -28.25, -16.09]} rotation={[0, 0.7, 0]} scale={[0.46, 0.74, 0.48]} />
        <mesh geometry={nodes.S_Antiparras.geometry} material={materials.MI_Antiparras} position={[19.51, -9.59, -16.7]} rotation={[0, -0.36, 0]} scale={[0.58, 1, 0.69]} />
        <mesh geometry={nodes.S_Basurero.geometry} material={materials.MI_Basurero} position={[-46.52, -9.5, -16.9]} rotation={[0, 1.57, 0]} scale={[0.67, 0.94, 0.52]} />
        <mesh geometry={nodes.S_CapsulaAmalgama3.geometry} material={materials.MI_CapsulaAmalgama} position={[-33.12, -9.19, -8.56]} rotation={[-1.62, -0.03, 1.39]} scale={[1.06, 0.84, 1.5]} />
        <mesh geometry={nodes.S_Copella.geometry} material={materials.MI_Copela} position={[-12.64, -8.8, -10.66]} rotation={[0, 1.57, 0]} scale={[0.31, 0.44, 0.24]} />
        <mesh geometry={nodes.S_CubetaMaxilarSupconAlginatoListo_HP_Cubeta_maxilar_su_e23460c.geometry} material={materials.M_Metal_Brushed_Nickel} position={[-45.79, -0.84, 17.01]} rotation={[Math.PI, Math.PI / 2, 0]} scale={[-0.04, -0.05, -0.03]} />
        <mesh geometry={nodes.S_DosificadorDeAguayPolvoOdontologia.geometry} material={materials.MI_PlasticAcrilico} position={[-97.59, -7.59, -11.43]} rotation={[0, 1.57, 0]} scale={[0.44, 0.62, 0.35]} />
        <mesh geometry={nodes.S_EscobillaDeProfilaxis.geometry} material={materials.MI_EscobillaProfilaxis} position={[-31.1, -8.99, -12.91]} rotation={[-1.65, 0.08, 0.53]} scale={[1.2, 1.35, 2]} />
        <mesh geometry={nodes.S_EspatulaDeAlginato.geometry} material={materials['Material.001']} position={[-31.76, -8.7, -7.33]} rotation={[-Math.PI, 0.87, -Math.PI]} scale={[0.94, 1.44, 0.9]} />
        <mesh geometry={nodes.S_EspatulaDeCemento.geometry} material={materials.MI_EspatulaCemento} position={[-40.51, -5.26, -13.85]} rotation={[-Math.PI / 2, 1.57, 0]} scale={[1.3, 0.92, 1.37]} />
        <mesh geometry={nodes.S_EyectorDesechable6.geometry} material={materials.MI_Eyector} position={[-39.53, -8.81, 15.45]} rotation={[1.52, -0.03, -1.75]} scale={[0.71, 0.56, 1]} />
        <mesh geometry={nodes.S_Fresarios.geometry} material={materials.MI_Fresarios} position={[-32.79, -8.44, 6.12]} scale={[0.56, 1, 0.71]} />
        <mesh geometry={nodes.S_FresasyGomasdePulido.geometry} material={materials.MI_FresasYGomasPulido} position={[-35, 2.83, -9.91]} rotation={[0, -1.57, 0]} scale={[0.21, 0.3, 0.17]} />
        <group position={[-43.51, 1.5, -18.16]} rotation={[0, -0.36, 0]} scale={[0.09, 0.16, 0.11]}>
          <mesh geometry={nodes.S_LamparaFotocurado_HP_1.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.S_LamparaFotocurado_HP_2.geometry} material={materials.Material_001} />
          <mesh geometry={nodes.S_LamparaFotocurado_HP_3.geometry} material={materials.Material_003} />
          <mesh geometry={nodes.S_LamparaFotocurado_HP_4.geometry} material={materials.Material_002} />
          <mesh geometry={nodes.S_LamparaFotocurado_HP_5.geometry} material={materials.Material_004} />
          <mesh geometry={nodes.S_LamparaFotocurado_HP_6.geometry} material={materials.Material_005} />
        </group>
        <mesh geometry={nodes.S_MicroBrush.geometry} material={materials.MI_Microbrush} position={[-35.56, 2.23, 20.05]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[0.6, 0.33, 0.43]} />
        <mesh geometry={nodes.S_Mortero_HP_Cylinder_004.geometry} material={materials.MI_Mortero} position={[16.43, -9.65, 8.62]} rotation={[0, Math.PI / 2, 0]} scale={[0.47, 0.66, 0.36]} />
        <mesh geometry={nodes.S_Mortero_HP_Cylinder_005.geometry} material={materials.MI_Mortero} position={[16.43, -9.65, 8.62]} rotation={[0, Math.PI / 2, 0]} scale={[0.47, 0.66, 0.36]} />
        <mesh geometry={nodes.S_PastaProfilactica.geometry} material={materials.MI_PastaProfilactica} position={[-41.02, -6.53, 4.17]} rotation={[-Math.PI, 1.04, -Math.PI]} scale={[0.68, 1, 0.6]} />
        <mesh geometry={nodes.S_pinzaMiller_HP.geometry} material={materials.M_Metal_Chrome} position={[-40.02, 2.33, 10.83]} rotation={[-1.66, -0.02, 1.21]} scale={[0.2, 0.16, 0.28]} />
        <mesh geometry={nodes.S_SondaPeriodontal.geometry} material={materials.MI_SondaPeridontal} position={[-39.33, 3.03, 6.77]} rotation={[-1.62, -0.03, 1.39]} scale={[1.23, 0.61, 1.73]} />
        <mesh geometry={nodes.S_Torula.geometry} material={materials.MI_Algodon} position={[-12.73, -5.73, -13.02]} rotation={[-0.27, 1.39, 1.13]} scale={[1.73, 1.64, 1.08]} />
        <mesh geometry={nodes.S_Torula2.geometry} material={materials.MI_Algodon} position={[-11.31, -9.54, -11.55]} rotation={[-0.27, 1.39, 1.13]} scale={[1.73, 1.64, 1.08]} />
        <mesh geometry={nodes.S_Torula3.geometry} material={materials.MI_Algodon} position={[-13.92, -8.8, -11.76]} rotation={[-3.11, 0.59, -2.33]} scale={[1.68, 1.56, 1.26]} />
        <mesh geometry={nodes.S_Torula4.geometry} material={materials.MI_Algodon} position={[-12.96, -7.35, -9.88]} rotation={[-0.27, 1.39, 1.13]} scale={[1.73, 1.64, 1.08]} />
        <mesh geometry={nodes.S_TuboDeResinaCompuesta.geometry} material={materials.MI_TuboResinaCompuesta} position={[-38.87, 1.64, 15.9]} scale={[0.43, 0.77, 0.55]} />
        <mesh geometry={nodes.S_Vaso_solo_HP.geometry} material={materials.vaso_alguinato} position={[-33.45, -6.6, -14.89]} rotation={[0, 1.57, 0]} scale={[0.02, 0.02, 0.01]} />
        <mesh geometry={nodes.S_VasoDappen.geometry} material={materials.MI_VasoDappen} position={[19.67, -9.42, -2.46]} scale={[0.56, 1, 0.71]} />
        <mesh geometry={nodes.S_VasoDappen2.geometry} material={materials.MI_VasoDappen} position={[18.76, -9.42, -6.8]} scale={[0.56, 1, 0.71]} />
        <mesh geometry={nodes.S_VasoDesechable6.geometry} material={materials.MI_VasoDesechable} position={[-31.09, -6.36, 18.17]} rotation={[0, 1.57, 0]} scale={[0.71, 1, 0.56]} />
        <mesh geometry={nodes.SM_Laboratory_Table_3.geometry} material={materials.Inst_Tables_and_Curbstone_01} position={[-68.81, -85, -4.19]} scale={[0.56, 1, 0.71]} />
        <mesh geometry={nodes.SM_Medical_Curbstone_Drawer_10.geometry} material={materials.Inst_Laboratory_Furniture_03} position={[-111.62, -26.23, 18.91]} scale={[0.69, 1.33, 0.88]} />
        <mesh geometry={nodes.SM_Medical_Curbstone_Drawer_11.geometry} material={materials.Inst_Laboratory_Furniture_03} position={[-82.88, -26.23, 18.91]} scale={[0.67, 1.33, 0.88]} />
        <mesh geometry={nodes.SM_Medical_Curbstone_Drawer_12.geometry} material={materials.Inst_Laboratory_Furniture_03} position={[-55.02, -26.23, 18.91]} scale={[0.67, 1.33, 0.88]} />
        <mesh geometry={nodes.SM_Table_on_Wheels_01.geometry} material={materials.Inst_Table_on_Wheels_01} position={[2.05, -85, -2.38]} scale={[0.56, 1, 0.71]} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/Mesa_2.glb')
